const formalunit = [
    { id: 1, formalName: "BAGS", formalCode: "BAG" },
    { id: 2, formalName: "BALE", formalCode: "BAL" },
    { id: 3, formalName: "BUNDLES", formalCode: "BDL" },
    { id: 4, formalName: "BUCKLES", formalCode: "BKL" },
    { id: 5, formalName: "BILLIONS OF UNITS", formalCode: "BOU" },
    { id: 6, formalName: "BOX", formalCode: "BOX" },
    { id: 7, formalName: "BOTTLES", formalCode: "BTL" },
    { id: 8, formalName: "BUNCHES", formalCode: "BUN" },
    { id: 9, formalName: "CANS", formalCode: "CAN" },
    { id: 10, formalName: "CUBIC METER", formalCode: "CBM" },
    { id: 11, formalName: "CUBIC CENTIMETER", formalCode: "CCM" },
    { id: 12, formalName: "CENTIMETER", formalCode: "CMS" },
    { id: 13, formalName: "CARTONS", formalCode: "CTN" },
    { id: 14, formalName: "DOZEN", formalCode: "DOZ" },
    { id: 15, formalName: "DRUM", formalCode: "DRM" },
    { id: 16, formalName: "GREAT GROSS", formalCode: "GGR" },
    { id: 17, formalName: "GRAMS", formalCode: "GMS" },
    { id: 18, formalName: "GROSS", formalCode: "GRS" },
    { id: 19, formalName: "GROSS YARDS", formalCode: "GYD" },
    { id: 20, formalName: "KILOGRAMS", formalCode: "KGS" },
    { id: 21, formalName: "KILOLITER", formalCode: "KLR" },
    { id: 22, formalName: "KILOMETRE", formalCode: "KME" },
    { id: 23, formalName: "MILLILITRE", formalCode: "MLT" },
    { id: 24, formalName: "METERS", formalCode: "MTR" },
    { id: 25, formalName: "METRIC TONS", formalCode: "MTS" },
    { id: 26, formalName: "NUMBERS", formalCode: "NOS" },
    { id: 27, formalName: "PACKS", formalCode: "PAC" },
    { id: 28, formalName: "PIECES", formalCode: "PCS" },
    { id: 29, formalName: "PAIRS", formalCode: "PRS" },
    { id: 30, formalName: "QUINTAL", formalCode: "QTL" },
    { id: 31, formalName: "ROLLS", formalCode: "ROL" },
    { id: 32, formalName: "SETS", formalCode: "SET" },
    { id: 33, formalName: "SQUARE FEET", formalCode: "SQF" },
    { id: 34, formalName: "SQUARE METERS", formalCode: "SQM" },
    { id: 35, formalName: "SQUARE YARDS", formalCode: "SQY" },
    { id: 36, formalName: "TABLETS", formalCode: "TBS" },
    { id: 37, formalName: "TEN GROSS", formalCode: "TGM" },
    { id: 38, formalName: "THOUSANDS", formalCode: "THD" },
    { id: 39, formalName: "TONNES", formalCode: "TON" },
    { id: 40, formalName: "TUBES", formalCode: "TUB" },
    { id: 41, formalName: "US GALLONS", formalCode: "UGS" },
    { id: 42, formalName: "UNITS", formalCode: "UNT" },
    { id: 43, formalName: "YARDS", formalCode: "YDS" },
    { id: 44, formalName: "OTHERS", formalCode: "OTH" }
  ];


  export default formalunit;