const sac = [
    { id: 1, description: "Labour Charges", saccode: "998540", gstrate: 0.18 },
    { id: 2, description: "cleaning Services", saccode: "9944", gstrate: 0.18 },
    { id: 3, description: "Software Services", saccode: "1044", gstrate: 0.18 },
    { id: 4, description: "Teaching Services", saccode: "1144", gstrate: 0.18 },
    { id: 5, description: "Hotel Accommodation", saccode: "9955", gstrate: 0.12 },
    { id: 6, description: "Transport of Goods", saccode: "9945", gstrate: 0.18 },
    { id: 7, description: "Manufacture of Goods", saccode: "9971", gstrate: 0.12 },
    { id: 8, description: "Supply of Electricity", saccode: "9990", gstrate: 5.5 },
    { id: 9, description: "Supply of Gas", saccode: "9991", gstrate: 18 },
    { id: 10, description: "Tour Operators Services", saccode: "9966", gstrate: 0.18 },
    { id: 11, description: "Construction Services", saccode: "9954", gstrate: 0.18 },
    { id: 12, description: "Telecom Services", saccode: "9988", gstrate: 18 },
    { id: 13, description: "Financial Services", saccode: "9959", gstrate: 18 },
    { id: 14, description: "Healthcare Services", saccode: "9983", gstrate: 12 },
    { id: 15, description: "Education Services", saccode: "9981", gstrate: 12 },
    { id: 16, description: "Agricultural Services", saccode: "9960", gstrate: 12 },
    { id: 17, description: "Tourism Services", saccode: "9961", gstrate: 12 },
    { id: 18, description: "Legal Services", saccode: "9964", gstrate: 18 },
    { id: 19, description: "Auditing Services", saccode: "9963", gstrate: 18 },
    { id: 20, description: "Accounting Services", saccode: "9962", gstrate: 18 },
    { id: 21, description: "Legal Services relating to Banking and Insurance", saccode: "996410", gstrate: 18 },
    { id: 22, description: "Legal Services relating to Intellectual Property", saccode: "996420", gstrate: 18 },
    { id: 23, description: "Legal Services relating to Civil and Criminal Matters", saccode: "996430", gstrate: 18 },
    { id: 24, description: "Legal Services relating to Labour and Employment Matters", saccode: "996440", gstrate: 18 },
    { id: 25, description: "Legal Services relating to Corporate and Commercial Matters", saccode: "996450", gstrate: 18 },
    { id: 26, description: "Legal Services relating to Taxation Matters", saccode: "996460", gstrate: 18 },
    { id: 27, description: "Legal Services relating to Family Law Matters", saccode: "996470", gstrate: 18 },
    { id: 28, description: "Legal Services relating to Property Law Matters", saccode: "996480", gstrate: 18 },
    { id: 29, description: "Legal Services relating to Consumer Protection Matters", saccode: "996490", gstrate: 18 },
    { id: 30, description: "Legal Services relating to Environmental Matters", saccode: "996500", gstrate: 18 },
    { id: 31, description: "Legal Services relating to Arbitration and Conciliation Matters", saccode: "996510", gstrate: 18 },
    { id: 32, description: "Legal Services relating to Other Matters", saccode: "996520", gstrate: 18 },
    { id: 33, description: "Accounting Services relating to Banking and Insurance", saccode: "996210", gstrate: 18 },
    { id: 34, description: "Accounting Services relating to Intellectual Property", saccode: "996220", gstrate: 18 },
    { id: 35, description: "Accounting Services relating to Civil and Criminal Matters", saccode: "996230", gstrate: 18 },
    { id: 36, description: "Accounting Services relating to Labour and Employment Matters", saccode: "996240", gstrate: 18 },
    { id: 37, description: "Accounting Services relating to Corporate and Commercial Matters", saccode: "996250", gstrate: 18 },
    { id: 38, description: "Accounting Services relating to Taxation Matters", saccode: "996260", gstrate: 18 },
    { id: 39, description: "Accounting Services relating to Family Law Matters", saccode: "996270", gstrate: 18 },
    { id: 40, description: "Accounting Services relating to Property Law Matters", saccode: "996280", gstrate: 18 },
    { id: 41, description: "Accounting Services relating to Consumer Protection Matters", saccode: "996290", gstrate: 18 },
{ id: 42, description: "Accounting Services relating to Environmental Matters", saccode: "996300", gstrate: 18 },
{ id: 43, description: "Accounting Services relating to Arbitration and Conciliation Matters", saccode: "996310", gstrate: 18 },
{ id: 44, description: "Accounting Services relating to Other Matters", saccode: "996320", gstrate: 18 },
{ id: 45, description: "Auditing Services relating to Banking and Insurance", saccode: "996330", gstrate: 18 },
{ id: 46, description: "Auditing Services relating to Intellectual Property", saccode: "996340", gstrate: 18 },
{ id: 47, description: "Auditing Services relating to Civil and Criminal Matters", saccode: "996350", gstrate: 18 },
{ id: 48, description: "Auditing Services relating to Labour and Employment Matters", saccode: "996360", gstrate: 18 },
{ id: 49, description: "Auditing Services relating to Corporate and Commercial Matters", saccode: "996370", gstrate: 18 },
{ id: 50, description: "Auditing Services relating to Taxation Matters", saccode: "996380", gstrate: 18 },
{ id: 51, description: "Auditing Services relating to Family Law Matters", saccode: "996390", gstrate: 18 },
{ id: 52, description: "Auditing Services relating to Property Law Matters", saccode: "996400", gstrate: 18 },
{ id: 53, description: "Auditing Services relating to Consumer Protection Matters", saccode: "996410", gstrate: 18 },
{ id: 54, description: "Auditing Services relating to Environmental Matters", saccode: "996420", gstrate: 18 },
{ id: 55, description: "Auditing Services relating to Arbitration and Conciliation Matters", saccode: "996430", gstrate: 18 },
{ id: 56, description: "Auditing Services relating to Other Matters", saccode: "996440", gstrate: 18 },
{ id: 57, description: "Management Consultancy Services relating to Banking and Insurance", saccode: "996110", gstrate: 18 },
{ id: 58, description: "Management Consultancy Services relating to Intellectual Property", saccode: "996120", gstrate: 18 },
{ id: 59, description: "Management Consultancy Services relating to Civil and Criminal Matters", saccode: "996130", gstrate: 18 },
{ id: 60, description: "Management Consultancy Services relating to Labour and Employment Matters", saccode: "996140", gstrate: 18 },
{ id: 61, description: "Management Consultancy Services relating to Corporate and Commercial Matters", saccode: "996150", gstrate: 18 },
{ id: 62, description: "Management Consultancy Services relating to Taxation Matters", saccode: "996160", gstrate: 18 },
{ id: 63, description: "Management Consultancy Services relating to Family Law Matters", saccode: "996170", gstrate: 18 },
{ id: 64, description: "Management Consultancy Services relating to Property Law Matters", saccode: "996180", gstrate: 18 },
{ id: 65, description: "Management Consultancy Services relating to Consumer Protection Matters", saccode: "996190", gstrate: 18 },
{ id: 66, description: "Management Consultancy Services relating to Environmental Matters", saccode: "996200", gstrate: 18 },
{ id: 67, description: "Management Consultancy Services relating to Arbitration and Conciliation Matters", saccode: "996210", gstrate: 18 },
{ id: 68, description: "Management Consultancy Services relating to Other Matters", saccode: "996220", gstrate: 18 },
{ id: 69, description: "Technical Testing and Analysis Services relating to Banking and Insurance", saccode: "996530", gstrate: 18 },
{ id: 70, description: "Technical Testing and Analysis Services relating to Intellectual Property", saccode: "996540", gstrate: 18 },
{ id: 71, description: "Technical Testing and Analysis Services relating to Civil and Criminal Matters", saccode: "996550", gstrate: 18 },
{ id: 72, description: "Technical Testing and Analysis Services relating to Labour and Employment Matters", saccode: "996560", gstrate: 18 },
{ id: 73, description: "Technical Testing and Analysis Services relating to Corporate and Commercial Matters", saccode: "996570", gstrate: 18 },
{ id: 74, description: "Technical Testing and Analysis Services relating to Taxation Matters", saccode: "996580", gstrate: 18 },
{ id: 75, description: "Technical Testing and Analysis Services relating to Family Law Matters", saccode: "996590", gstrate: 18 },
{ id: 76, description: "Technical Testing and Analysis Services relating to Property Law Matters", saccode: "996600", gstrate: 18 },
{ id: 77, description: "Technical Testing and Analysis Services relating to Consumer Protection Matters", saccode: "996610", gstrate: 18 },
{ id: 78, description: "Technical Testing and Analysis Services relating to Environmental Matters", saccode: "996620", gstrate: 18 },
{ id: 79, description: "Technical Testing and Analysis Services relating to Arbitration and Conciliation Matters", saccode: "996630", gstrate: 18 },
{ id: 80, description: "Technical Testing and Analysis Services relating to Other Matters", saccode: "996640", gstrate: 18 },
{ id: 81, description: "Architectural Services", saccode: "9972", gstrate: 12 },
{ id: 82, description: "Engineering Services", saccode: "9973", gstrate: 12 },
{ id: 83, description: "Surveying Services", saccode: "9974", gstrate: 12 },
{ id: 84, description: "Town Planning Services", saccode: "9975", gstrate: 12 },
{ id: 85, description: "Interior Designing Services", saccode: "9976", gstrate: 12 },
{ id: 86, description: "Landscape Designing Services", saccode: "9977", gstrate: 12 },
{ id: 87, description: "Advertising Services", saccode: "9982", gstrate: 18 },
{ id: 88, description: "Market Research Services", saccode: "9984", gstrate: 18 },
{ id: 89, description: "Public Relations Services", saccode: "9985", gstrate: 18 },
{ id: 90, description: "Telemarketing Services", saccode: "9986", gstrate: 18 },
{ id: 91, description: "Business Process Outsourcing Services", saccode: "9987", gstrate: 18 },
{ id: 92, description: "Call Centre Services", saccode: "9988", gstrate: 18 },
{ id: 93, description: "Data Processing Services", saccode: "9989", gstrate: 18 },
{ id: 94, description: "Data Entry Services", saccode: "9990", gstrate: 18 },
{ id: 95, description: "Data Conversion Services", saccode: "9991", gstrate: 18 },
{ id: 96, description: "Data Back-up Services", saccode: "9992", gstrate: 18 },
{ id: 97, description: "Data Recovery Services", saccode: "9993", gstrate: 18 },
{ id: 98, description: "Data Security Services", saccode: "9994", gstrate: 18 },
{ id: 99, description: "Information Technology Consulting Services", saccode: "9995", gstrate: 18 },
{ id: 100, description: "Computer Software Services", saccode: "1044", gstrate: 18 },
{ id: 101, description: "Computer Hardware Services", saccode: "9997", gstrate: 18 },
{ id: 102, description: "Computer Networking Services", saccode: "9998", gstrate: 18 },
{ id: 103, description: "Computer Maintenance Services", saccode: "9999", gstrate: 18 },
{ id: 104, description: "E-commerce Services", saccode: "9956", gstrate: 18 },
{ id: 105, description: "E-learning Services", saccode: "9957", gstrate: 18 },
{ id: 106, description: "Recharge and Bill Payment Services", saccode: "9967", gstrate: 18 },
{ id: 107, description: "Mobile VAS Services", saccode: "9968", gstrate: 18 },
{ id: 108, description: "SMS Services", saccode: "9969", gstrate: 18 },
{ id: 109, description: "Data Centre Services", saccode: "9970", gstrate: 18 },
{ id: 110, description: "Cloud Computing Services", saccode: "9971", gstrate: 18 },
{ id: 111, description: "Website Designing and Development Services", saccode: "9952", gstrate: 18 },
{ id: 112, description: "Web Hosting Services", saccode: "9953", gstrate: 18 },
{ id: 113, description: "Search Engine Optimization Services", saccode: "9958", gstrate: 18 },
{ id: 114, description: "Social Media Marketing Services", saccode: "9950", gstrate: 18 },
{ id: 115, description: "Online Advertising Services", saccode: "9982", gstrate: 18 },
{ id: 116, description: "E-ticketing Services", saccode: "9978", gstrate: 18 },
{ id: 117, description: "E-wallet Services", saccode: "9979", gstrate: 18 },
{ id: 118, description: "Payment Gateway Services", saccode: "9980", gstrate: 18 },
{ id: 119, description: "Loyalty Programme Services", saccode: "9981", gstrate: 18 },
{ id: 120, description: "Other Business Services", saccode: "9996", gstrate: 18 },
{ id: 121, description: "Telephone and Telegraph Services", saccode: "9943", gstrate: 18 },
{ id: 122, description: "Postal Services", saccode: "9942", gstrate: 18 },
{ id: 123, description: "Courier Services", saccode: "9941", gstrate: 18 },
{ id: 124, description: "Freight Forwarding Services", saccode: "9940", gstrate: 18 },
{ id: 125, description: "Warehousing Services", saccode: "9939", gstrate: 18 },
{ id: 126, description: "Cargo Handling Services", saccode: "9938", gstrate: 18 },
{ id: 127, description: "Air Freight Services", saccode: "9937", gstrate: 18 },
{ id: 128, description: "Sea Freight Services", saccode: "9936", gstrate: 18 },
{ id: 129, description: "Rail Freight Services", saccode: "9935", gstrate: 18 },
{ id: 130, description: "Road Freight Services", saccode: "9934", gstrate: 18 },
{ id: 131, description: "Distribution Services", saccode: "9933", gstrate: 18 },
{ id: 132, description: "Logistics Services", saccode: "9932", gstrate: 18 },
{ id: 133, description: "Travel and Tourism Services", saccode: "9920", gstrate: 18 },
{ id: 134, description: "Hotel and Restaurant Services", saccode: "9927", gstrate: 18 },
{ id: 135, description: "Transport Services", saccode: "9930", gstrate: 18 },
{ id: 136, description: "Leisure and Entertainment Services", saccode: "9921", gstrate: 18 },
{ id: 137, description: "Education and Training Services", saccode: "9919", gstrate: 18 },
{ id: 138, description: "Healthcare Services", saccode: "9918", gstrate: 18 },
{ id: 139, description: "Other Services", saccode: "9995", gstrate: 18 },
{ id: 140, description: "SAC Code Not Available", saccode: "0", gstrate: 0 },
{ id: 141, description: "Legal Services", saccode: "9901", gstrate: 18 },
{ id: 142, description: "Accounting Services", saccode: "9902", gstrate: 18 },
{ id: 143, description: "Auditing Services", saccode: "9903", gstrate: 18 },
{ id: 144, description: "Business Advisory Services", saccode: "9904", gstrate: 18 },
{ id: 145, description: "Management Consulting Services", saccode: "9905", gstrate: 18 },
{ id: 146, description: "Market Research Services", saccode: "9906", gstrate: 18 },
{ id: 147, description: "Advertising Services", saccode: "9907", gstrate: 18 },
{ id: 148, description: "Public Relations Services", saccode: "9908", gstrate: 18 },
{ id: 149, description: "Exhibition Services", saccode: "9909", gstrate: 18 },
{ id: 150, description: "Recruitment Services", saccode: "9910", gstrate: 18 },
{ id: 151, description: "Employment Services", saccode: "9911", gstrate: 18 },
{ id: 152, description: "Temporary Staffing Services", saccode: "9912", gstrate: 18 },
{ id: 153, description: "Outsourcing Services", saccode: "9913", gstrate: 18 },
{ id: 154, description: "Human Resource Management Services", saccode: "9914", gstrate: 18 },
{ id: 155, description: "Training Services", saccode: "9915", gstrate: 18 },
{ id: 156, description: "Education Services", saccode: "9916", gstrate: 18 },
{ id: 157, description: "Training and Placement Services", saccode: "9917", gstrate: 18 },
{ id: 158, description: "Cultural Services", saccode: "9918", gstrate: 18 },
{ id: 159, description: "Sports and Recreation Services", saccode: "9919", gstrate: 18 },
{ id: 160, description: "Other Business Services", saccode: "9920", gstrate: 18 },
{ id: 161, description: "Legal Process Outsourcing", saccode: "9921", gstrate: 18 },
{ id: 162, description: "Data Entry Services", saccode: "9922", gstrate: 18 },
{ id: 163, description: "Data Processing Services", saccode: "9923", gstrate: 18 },
{ id: 164, description: "Web Designing Services", saccode: "9924", gstrate: 18 },
{ id: 165, description: "Web Hosting Services", saccode: "9925", gstrate: 18 },
{ id: 166, description: "Search Engine Optimization Services", saccode: "9926", gstrate: 18 },
{ id: 167, description: "Content Writing Services", saccode: "9927", gstrate: 18 },
{ id: 168, description: "Translation Services", saccode: "9928", gstrate: 18 },
{ id: 169, description: "Software Development Services", saccode: "9929", gstrate: 18 },
{ id: 170, description: "Hardware Maintenance Services", saccode: "9930", gstrate: 18 },
  ];

export default sac;